version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: symfony_php
    volumes:
      - .:/var/www
    working_dir: /var/www/app
    depends_on:
      - postgres
      - mongo

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/app/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: lovelire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: symfony_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
